import axios from './axios';

export const getAdminDashboard = () => axios.get('/admin/dashboard');
export const getDepartments = () => axios.get('/admin/departments');
export const createDepartment = (data) => axios.post('/admin/departments', data);
export const updateDepartment = (id, data) => axios.put(`/admin/departments/${id}`, data);
export const getDeptStaff = (params) => axios.get('/admin/dept-staff', { params });
export const createDeptStaff = (data) => axios.post('/admin/dept-staff', data);
export const updateDeptStaff = (id, data) => axios.put(`/admin/dept-staff/${id}`, data);
export const deleteDeptStaff = (id) => axios.delete(`/admin/dept-staff/${id}`);
export const getAdminTeachers = (params) => axios.get('/admin/teachers', { params });
export const getAdminStudents = (params) => axios.get('/admin/students', { params });
export const getEnrollmentReport = (params) => axios.get('/admin/reports/enrollment', { params });
export const bulkUploadStudents = (formData) => axios.post('/admin/bulk-upload/students', formData, { headers: { 'Content-Type': 'multipart/form-data' } });
export const getDepartmentOverview = (id) => axios.get(`/admin/departments/${id}`);
export const getDepartmentStudents = (id, params) => axios.get(`/admin/departments/${id}/students`, { params });
export const getDepartmentTeachers = (id) => axios.get(`/admin/departments/${id}/teachers`);
export const getDepartmentResults = (id) => axios.get(`/admin/departments/${id}/results`);
export const getSemesterResultBoard = (semesterId) => axios.get(`/admin/results/${semesterId}/board`);
export const downloadResultSheetPDF = (semesterId) => axios.get(`/admin/results/${semesterId}/pdf`, { responseType: 'blob' });
export const getDepartmentStaffAccess = (id) => axios.get(`/admin/departments/${id}/staff-access`);
export const createDepartmentStaffAccess = (id, data) => axios.post(`/admin/departments/${id}/staff-access`, data);
export const resetStaffPassword = (staffId) => axios.put(`/admin/staff/${staffId}/reset-password`);
export const toggleStaffStatus = (staffId, isActive) => axios.put(`/admin/staff/${staffId}/toggle-status`, { is_active: isActive });
export const revokeStaffAccess = (staffId) => axios.delete(`/admin/staff/${staffId}`);
export const globalUserSearch = (query) => axios.get('/admin/users/search', { params: { q: query } });
export const updateGlobalUser = (role, id, data) => axios.put(`/admin/users/${role}/${id}`, data);
export const createAdmin = (data) => axios.post('/admin/admins', data);
export const getGradingScale = () => axios.get('/admin/settings/grading-scale');
export const updateGradingScale = (data) => axios.put('/admin/settings/grading-scale', data);
export const getMarksConfig = () => axios.get('/admin/settings/marks-config');
export const updateMarksConfig = (data) => axios.put('/admin/settings/marks-config', data);
